version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - mv target/zfile-3.2.5.jar zfile-eb.jar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - zfile-eb.jar
    - .ebextensions/**/*