version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/zfile-eb.zip zfile-eb.zip
artifacts:
  files:
    - zfile-eb.zip
    - .ebextensions/**/*