
    create table driver_config (
       id integer not null,
        auto_refresh_cache boolean,
        default_switch_to_img_mode boolean,
        enable boolean,
        enable_cache boolean,
        name varchar(255),
        order_num integer,
        search_contain_encrypted_file boolean,
        search_enable boolean,
        search_ignore_case boolean,
        type varchar(255),
        primary key (id)
    )

    create table filter_config (
       id integer generated by default as identity,
        drive_id integer,
        expression varchar(255),
        primary key (id)
    )

    create table short_link (
       id integer generated by default as identity,
        create_date timestamp,
        key_name varchar(255),
        url varchar(255),
        primary key (id)
    )

    create table storage_config (
       id integer generated by default as identity,
        drive_id integer,
        k varchar(255),
        title varchar(255),
        type varchar(255),
        value clob,
        primary key (id)
    )

    create table system_config (
       id integer generated by default as identity,
        k varchar(255),
        remark varchar(255),
        value clob,
        primary key (id)
    )
