#########################
#
#  Zfile
#
#########################
zfile:
  debug: true
  webdav: false
  directLinkPrefix: directlink
  log:
    path: ${user.home}/.zfile/logs
  db:
    path: ${user.home}/.zfile/db/zfile
  tmp:
    path: ${user.home}/.zfile/tmp
  cache:
    auto-refresh:
      interval: 1
    timeout: 1800
  constant:
    readme: readme.md
    password: password.txt
  preview:
    audio:
      maxFileSizeMb: 5
    text:
      maxFileSizeKb: 512
  onedrive:
    clientId: 09939809-c617-43c8-a220-a93c1513c5d4
    clientSecret: _l:zI-_yrW75lV8M61K@z.I2K@B/On6Q
    redirectUri: https://zfile.jun6.net/onedrive/callback
    scope: offline_access User.Read Files.ReadWrite.All
  onedrive-china:
    clientId: 4a72d927-1907-488d-9eb2-1b465c53c1c5
    clientSecret: Y9CEA=82da5n-y_]KAWAgLH3?R9xf7Uw
    redirectUri: https://zfile.jun6.net/onedrive/china-callback
    scope: offline_access User.Read Files.ReadWrite.All


#########################
#
#  Server
#
#########################
server:
  # port: 8080
  port: 5000   # AWS Elastic Beanstalkに利用する
  servlet:
    context-path: ''
  tomcat:
    threads:
      max: 20
  compression:
    enabled: true


#########################
#
#  Datasource
#
#########################
spring:
  # H2 for debug tool
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: ${zfile.debug}
  
  # Connection
  datasource:
    # h2 内存数据库 配置
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:${zfile.db.path}
    url: jdbc:h2:mem:zfile  # ←インメモリDB
    #username: zfile
    #password: 123456

    # MySQL 配置
     # driver-class-name: com.mysql.jdbc.Driver
     # url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
     # username: javaapp
     # password: Javaapp_1123
    
    # druid setting
    type: com.alibaba.druid.pool.DruidDataSource


  # JSON
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    generate-ddl: true
    defer-datasource-initialization: true
    
  # Profile
  profiles:
    active: prod

  # Initialize data import
  sql:
    init:
      continue-on-error: true
      mode: always
      data-locations: classpath*:db/data.sql
      encoding: utf-8