package im.zhaojun.zfile.model.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

/**
 * @author zhaojun
 */
@DynamoDBTable(tableName = "system_config")
@Entity(name = "system_config")
@Data
public class SystemConfig {

	//	@Id
	//	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey()
	private Integer id;

	@Column(name = "k")
	private String key;

	@Lob
	private String value;

	private String remark;

}
