package im.zhaojun.zfile.model.entity.dynamoDb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "system_config")
public class SystemConfig {

	private String id;

	//@Column(name = "k")
	private String keyName;

	//@Lob
	private String value;

	private String remark;

	public SystemConfig() {
	}

	public SystemConfig(String id, String key, String remark, String value) {
		this.id = id;
		this.keyName = key;
		this.value = value;
		this.remark = remark;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getKeyName() {
		return keyName;
	}

	public void setKeyName(String key) {
		this.keyName = key;
	}

	@DynamoDBAttribute
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@DynamoDBAttribute
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "SystemConfig [id=" + id + ", keyName=" + keyName + ", value=" + value + ", remark=" + remark + "]";
	}

}
