-- DRIVER_CONFIG
INSERT INTO PUBLIC.DRIVER_CONFIG
(ID, AUTO_REFRESH_CACHE, DEFAULT_SWITCH_TO_IMG_MODE, ENABLE, ENABLE_CACHE, NAME, ORDER_NUM, SEARCH_CONTAIN_ENCRYPTED_FILE, SEARCH_ENABLE, SEARCH_IGNORE_CASE, "TYPE")
VALUES(1, false, false, true, false, 'local', NULL, false, false, false, 'local');

-- STORAGE_CONFIG
INSERT INTO PUBLIC.STORAGE_CONFIG
(ID, DRIVE_ID, K, TITLE, "TYPE", VALUE)
VALUES(35, 1, 'filePath', '文件路径', 'local', 'c:\skychen');

-- SYSTEM_CONFIG
INSERT INTO PUBLIC.SYSTEM_CONFIG
(K, REMARK, VALUE)
VALUES('', '', '');

-- SYSTEM_CONFIG
UPDATE PUBLIC.SYSTEM_CONFIG 
SET VALUE='jp.skychen'
WHERE ID='1';

UPDATE PUBLIC.SYSTEM_CONFIG 
SET VALUE='admin'
WHERE ID='6';

UPDATE PUBLIC.SYSTEM_CONFIG 
SET VALUE='21232f297a57a5a743894a0e4a801fc3'
WHERE ID='7';

UPDATE PUBLIC.SYSTEM_CONFIG 
SET VALUE='http://192.168.10.102:5000'
WHERE ID='8';